### PR TITLE
Update readme and sample to use latest android-apt version

### PR DESCRIPTION
**Pull request by MichaelEvans**

### CODE REVIEW

**Comment by MichaelEvans** [comment]
Also, seems like there's some random spaces in some of these files?

**Comment by felipecsl** [comment]
WAT?! also apparently doenst work with apt 1.7 as it failed to generate the classes

**Comment by MichaelEvans** [comment]
@felipecsl yeah I see that...not sure why, `./gradlew check assemble` worked for me locally. Ideas?

**Comment by felipecsl** [comment]
apparently if you assemble first and check after, it works fine. I'll merge this and update the travis script manually. thanks!

**Comment by MichaelEvans** [comment]
:+1: thanks! Didn't even notice that. Good eye!

**Pull request merged**
