### PR TITLE
block non-static method to avoid runtime exception

### PR DESCRIPTION
**Pull request by imlunacat**
If a non-static is annotated with `@DeepLink` and invoked by deeplink. Application would crash in method invocation.
i.e.
```java
// cause crash if airbnb://host/20 is retrieved
@DeepLink("airbnb://host/{arbitraryNumber}")
public Intent intentFromNoStatic(Context context) {
  return new Intent(context, MainActivity.class).setAction(ACTION_DEEP_LINK_COMPLEX);
}
```

Throw Exception in compile-time rather than crash in runtime.

### CODE REVIEW

**Comment by felipecsl** [comment]
Looks like checkstyle failed, can you fix it please? https://travis-ci.org/airbnb/DeepLinkDispatch/jobs/81404882
Also please add a unit test!
Thanks!

**Comment by imlunacat** [comment]
Hi felipecsl,
  It seems checkstyle fail is caused by `DeepLinkUri.java`. These fail should be fixed in this pull-request ?

**Comment by felipecsl** [comment]
you're right. that has been fixed on master already. just needs a test now!

**Comment by imlunacat** [comment]
Hello,
  Is there any update about this PR ?
  It seems all checks are passed and unit test is added now ;)

**Comment by felipecsl** [comment]
Looks good now. Mergin. Thanks!

**Pull request merged**
