### PR TITLE
Ensure a sorted DeepLinkEntry registry

### PR DESCRIPTION
**Pull request by jingwei423**
1 add logic to ensure a stable sorting result
2 move the doc generation after the sorting, so the doc is sorted

This is important for us: with sorted outputs we could decide whether
or not to trigger different downstream processes, so we can save time
on build tasks, and commit verifications

### CODE REVIEW

**Comment by felipecsl** [comment]
@jingwei423 can you look into the checkstyle failures? I can merge after that's green1

**Comment by jingwei423** [comment]
@felipecsl thanks for the review! Can we have a new release soon? So we can update our internal tools to depend on this change.

**Comment by jingwei423** [comment]
@felipecsl can we have a release for this?

**Comment by felipecsl** [comment]
Sure, we'll get one out soon!

**Comment by felipecsl** [comment]
v3.1.1 has been uploaded. It should be available soon

**Comment by jingwei423** [comment]
Awesome, thank you!

**Pull request merged**
