### PR TITLE
fix options not recognized by any processor warning

### PR DESCRIPTION
**Pull request by linnar**

### CODE REVIEW

**Comment by rossbacher** [comment]
Can you provide more details?

**Comment by linnar** [comment]
If I use the library with `annotationProcessor`, I get the following warning - `The following options were not recognized by any processor: '[deepLink.incremental, deepLink.customAnnotations]'`. However, it does not appears when used with `kapt`

**Comment by Charis1331** [comment]
This appears when using `kapt` too. Should we expect a merge soon? Thanks.

**Comment by Charis1331** [comment]
@rossbacher  Any news on this? Thanks.

**Comment by rossbacher** [comment]
I just published [5.2.0](https://github.com/airbnb/DeepLinkDispatch/releases/tag/5.2.0) with this fix included.

**Comment by alexfu** [comment]
I'm still getting this warning with 5.2.0 🤔 when using with `kapt`.

**Pull request merged**
