### PR TITLE
AndroidX migration

### PR DESCRIPTION
**Pull request by carvaq**
The processor generates support classes that are no longer compatible with projects running AndroidX. With theses changes the processor will look for and generate AndroidX classes.

Is related to issue #222

[AndroidX Release notes](https://developer.android.com/topic/libraries/support-library/androidx-rn)

### CODE REVIEW

**Comment by carvaq** [comment]
Hi @felipecsl 

I tried fixing the config, but I'm always getting an error about accepting the terms and conditions for the new build tools. On [this](https://stackoverflow.com/questions/38096225/automatically-accept-all-sdk-licences) StackOverflow post they suggest to  add `yes | sdkmanager --licenses`  to the travis config. I haven't had the chance to work with travis before, so I'm not entirely sure what the best approach would be.

**Comment by rossbacher** [comment]
@carvaq Can you try to add this to the travis yml file?

```
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
```

**Comment by rossbacher** [comment]
@carvaq I created https://github.com/carvaq/DeepLinkDispatch/pull/1 against your fork. This fixes the problem with the dependency and after that the PR should pass and we will be able to merge it soon.

**Comment by rossbacher** [comment]
Thank you @carvaq !

**Comment by tallnato** [comment]
When are you planning to do a release with this migration? 

I was trying to use it through Jitpack, but it seams that the `com.github.airbnb.DeepLinkDispatch:deeplinkdispatch:XXX` is not being included in the jitpack release  
https://jitpack.io/com/github/airbnb/DeepLinkDispatch/master-v3.1.1-g0ae5613-9/build.log

**Comment by semanticer** [comment]
When can we expect this or how can we work around it right now? Thank you for any help @carvaq @rossbacher

**Comment by rogerhu** [comment]
It's been over a year since a build got pushed (https://oss.sonatype.org/content/repositories/snapshots/com/airbnb/deeplinkdispatch/3.2.0-SNAPSHOT/).

My workaround has been to use composite builds with the `settings.gradle`:

```gradle
includeBuild('../DeepLinkDispatch') {
    dependencySubstitution {
        substitute module("com.airbnb:deeplinkdispatch-processor") with project(':deeplinkdispatch-processor')
        substitute module("com.airbnb:deeplinkdispatch") with project(':deeplinkdispatch')

    }
}
```

**Comment by rogerhu** [comment]
This PR https://github.com/airbnb/DeepLinkDispatch/pull/230 should also fix JitPack.Io snapshots:

 ```gradle
implementation "com.github.rogerhu.DeepLinkDispatch:deeplinkdispatch:maven-SNAPSHOT"
kapt "com.github.rogerhu.DeepLinkDispatch:deeplinkdispatch-processor:maven-SNAPSHOT"
```

**Pull request merged**
